### ISSUE TITLE
Selected language does not shows in holiday calendar

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#227]
**Describe the bug**
Selected language does not show in the holiday calendar

**To Reproduce**
1. My Calendar language is Dutch Belgian
2. Go to holiday settings, holiday calendar does not show selected language

Selected language does not show in the holiday calendar
https://www.screencast.com/t/dE5hSiRKbx9M

**Comment by ashokrane** [comment]
It's fine to leave this one as it is. None of our customers have asked for this in Lite or in Pro plugin. Hence closing it.
