### ISSUE TITLE
The delivery date is not showing on the Order Received page & in the email notifications

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#238]
**Describe the bug**
The client has reported a bug where the selected delivery date is not showing on the Order Received page nor in the email notifications.

**To Reproduce**
I am able to replicate this issue on client's site but not on my local server. 
Screenshot: https://prnt.sc/rlvp60
Screenshot of email: https://prnt.sc/rlvpk1

This issue is still coming even after deactivating all the plugins on the site.

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront]
- [ ] I can reproduce this bug consistently using the steps above

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/14775

**Comment by nitin-ts** [comment]
Hello,
I can not replicate it on my local.
I have checked this on the client's site and it is working fine now.

I got the delivery date on the order received page and in email too.

https://i.imgur.com/GglAMy8.png
https://i.imgur.com/UpkSp9v.png

So, I am closing this issue.
