### ISSUE TITLE
Calendar Date Picker not functioning in Safari 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#239]
**Describe the bug**
When we see the arrows do appear fine but the months don’t change in Safari. Screenshot: https://prnt.sc/rnwf1z

**To Reproduce**
I am also able to replicate this issue on woo_actest
1. Go to the Checkout page
2. Click  on Delivery Date
3. Click on arrow for changing the month. It won't change
4. It works fine in Chrome. 

**Expected behavior**
It should work in safari too.

.
**Desktop (please complete the following information):**
 - Browser [ safari ]

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

**Additional context**
Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/14968

**Comment by Chetna1510** [comment]
One more client has reported the issue: https://tychesoftwares.freshdesk.com/a/tickets/30731

**Comment by nitin-ts** [comment]
Hello,
I have checked this issue in the safari browser of Mac OS and it is working fine.
please see the below video: https://drive.google.com/file/d/1tTzGf1PbZZDUCV4XIuBnYCSDCuJYUuY-/view?usp=sharing

So, I am closing this issue.
