### ISSUE TITLE
Show a notice for exporting the plugin setting from Lite to Pro version of the plugin

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/order-delivery-date-for-woocommerce#26]
When someone installs Pro version when the lite version is already added, then a notice should be added to allow the user to export the settings from lite version to pro version.

This will ensure all the settings from lite version is will stay/ set in the Pro version.

The notice should have a Yes/ No links. Clicking on Yes should take you to a new page and show details of what all things will be exported to the Pro version.

**Comment by ashokrane** [comment]
This has been implemented in an earlier release, closing it.
