### ISSUE TITLE
Selected time slot are not passed from the cart page to checkout page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#263]
**Describe the bug**
Selected time slots are not passed from the cart to the checkout page.

**To Reproduce**
1. Date and time slot setup
2. "Delivery Date field on Cart page" setting enabled
3. Select delivery date and time slot on the cart page
4. checkout page shows the delivery date correctly but the time slot is not preselected.
https://www.screencast.com/t/HXHlNuCQ

**Expected behavior**
Time slot should be passed from cart to checkout page

**Comment by rashmimalpande** [comment]
This issue is fixed in the pull request #322
