### ISSUE TITLE
UNable to set MDT in decimals 

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/order-delivery-date-for-woocommerce#277]
Unable to set MDT in decimals. 

This is important for clients who have minimum preparation time in minutes like 30 mins or 90 mins or so on. 

Currently, this notice is coming: https://prnt.sc/ufgf5p

**Comment by ashokrane** [comment]
One more client has also asked for this: https://wordpress.org/support/topic/minimum-delivery-time-comma-value-not-valid/ .
