### ISSUE TITLE
Auto populate is not getting unchecked 

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/order-delivery-date-for-woocommerce#285]
**Describe the bug**
Auto-populate option is not getting unchecked.  

**To Reproduce**
Steps to reproduce the behaviour:
1. I unchecked the auto-populate option and clicked the saved button still the option is coming checked. 
2. Also, on the checkout page the date is getting auto-populated. 

Video: https://drive.google.com/file/d/1onRzu5SE6W6tGPn-u0LjJ3vr_obdWDGO/view 

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/20929

**Comment by Chetna1510** [comment]
This has been reported here too: https://wordpress.org/support/topic/cant-uncheck-auto-populate-delivery-date-option
