### ISSUE TITLE
The checkout page hangs when current day is not available in the delivery days 

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/order-delivery-date-for-woocommerce#286]
**Describe the bug**
The checkout page hangs when the current day is not available in the delivery days 

**To Reproduce**
Steps to reproduce the behaviour:
1. Today is Thursday and I have disabled that. So, the checkout page hangs when you visit that. 

Video: https://drive.google.com/file/d/1aEMH5NVuQegkqd5hM2113jq6p4_3j0uC/view 

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/20929

**Comment by Chetna1510** [comment]
One more client has reported this bug: https://wordpress.org/support/topic/endless-loading-on-checkout-page-2/
