### ISSUE TITLE
Minimum Delivery Time is not getting calculated correctly when we don't have all the weekdays enabled

### ISSUE THREAD

**Issue by upenkapse** [TycheSoftwares/order-delivery-date-for-woocommerce#287]
**Describe the bug**
Minimum Delivery Time is not getting calculated correctly when we don't have all the weekdays enabled

**To Reproduce**
1. Keep only Wednesday, Thursday, and Friday as delivery days, keep MDT to 58 hours, and also enable the Apply Minimum Delivery Time for non-working weekdays: option as you can see in this screenshot: https://prnt.sc/upb8z0
2. So, when we check this on Monday after 14:00, the first available delivery day should be the next Thursday. 
3. But it is showing Wednesday as the first available delivery day: https://prnt.sc/upbb2e

**Expected behavior**
After Monday 14:00, it should show Thursday as the first available delivery day. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront]
- [ ] I can reproduce this bug consistently using the steps above

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/20891

**Comment by Chetna1510** [comment]
This issue has been reported by another customer: https://tychesoftwares.freshdesk.com/a/tickets/21517

**Comment by Chetna1510** [comment]
One more client has reported this: https://tychesoftwares.freshdesk.com/a/tickets/21780

**Comment by upenkapse** [comment]
One more customer reported the issue:  https://tychesoftwares.freshdesk.com/a/tickets/21106

Setup: https://prnt.sc/v5a9dm

When I check on Thursday after 16:00, the next day(Friday) should not be available for selection, but it is allowing me to select Friday after 16:00 on Thursday: https://prnt.sc/v5abxc

**Comment by Chetna1510** [comment]
One more client has reported this bug: https://tychesoftwares.freshdesk.com/a/tickets/21772
