### ISSUE TITLE
Wrong delivery date is getting auto populated on the checkout page.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#288]
**Describe the bug**
. We do not deliver Mon,Sat,Sun yet customers have been able to select these. When I go on the Website it doesn't give this option so I don’t know how so many have managed to do this. screenshot: https://prnt.sc/urbggu

**To Reproduce**
Not able to replicate at our end.

**WordPress Environment**
<details>
```
**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/21022

**Comment by nitin-ts** [comment]
Hello,

with the same settings ( https://i.imgur.com/wp7oNAz.png ) as the client showed in their screenshots, it displays proper days based on the settings ( https://i.imgur.com/3ycBuSd.png ).

So I am closing this.
