### ISSUE TITLE
Saving empty holiday date removes all previously saved dates

### ISSUE THREAD

**Issue by michaelbragg** [TycheSoftwares/order-delivery-date-for-woocommerce#300]
**Describe the bug**

**To Reproduce**
1. WP Admin
2. Order Delivery Date
3. General Settings
4. Holidays
5. Enter details for Name, From Date, To Date
6. Save Settings
7. See Holiday shown
8. Save Settings with all fields empty / unchecked
9. All previous Holiday are removed.

**Expected behavior**
I would expect the Add Holiday form to either disable submission, or the holidays to not be removed on save of an empty form.

**Screenshots or Video**
If applicable, add screenshots or Video to help explain your problem.

![order_delivery_date_lite_holidays](https://user-images.githubusercontent.com/1015212/98837204-95829c00-243a-11eb-8273-03f581af31dc.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FireFox
 - Version 82.0.2 (64-bit)

**Isolating the problem (mark completed items with an [x]):**
- [ ] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

**WordPress Environment**
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.11
PHP Post Max Size: 128 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.15-MariaDB-1:10.4.15+maria~focal
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 166.94MB
Database Data Size: 99.34MB
Database Index Size: 67.60MB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Laps: by Andrey “Rarst” Savchenko – 3.3.3
Query Monitor: by John Blackbourn – 3.6.4
Advanced Custom Fields PRO: by Elliot Condon – 5.9.3
Crafty Clicks Postcode Lookup: by Crafty Clicks – 1.2.11
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.2
Limit Login Attempts Reloaded: by WPChef – 2.15.2
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.11.4 – Installed version not tested with active version of WooCommerce 4.7.0
Product/Review CSV Import Export: by WebToffee – 3.8.1
Safe Redirect Manager: by 10up – 1.9.3
Safe SVG: by Daryll Doyle – 1.9.9
SendGrid: by SendGrid – 1.11.8
SpinupWP: by Delicious Brains – 1.2
User Switching: by John Blackbourn & contributors – 1.5.6
WooCommerce All Products For Subscriptions: by SomewhereWarm 
WooCommerce Stripe Gateway: by WooCommerce – 4.5.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.24
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 3.1.4
WooCommerce Product Bundles: by SomewhereWarm – 6.5.1
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.16.1
WooCommerce Subscriptions: by WooCommerce – 3.0.10
WooCommerce: by Automattic – 4.7.0
Yoast SEO: by Team Yoast – 15.2.1 – Installed version not tested with active version of WooCommerce 4.7.0
New Relic Reporting for WordPress: by 10up – 1.3.1
WP Robots Txt: by Christopher Davis – 1.1

### Dropin Plugins (2) ###

db.php: Query Monitor Database Class
object-cache.php: SpinupWP Redis Object Cache Drop-In

### Must Use Plugins (5) ###

Bedrock Autoloader: by Roots – 1.0.0
Disallow Indexing: by Roots – 1.0.0
index.php: by  –
SpinupWP Debug Log Path: by Delicious Brains – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #89634 - /terms-and-conditions/

### Theme ###

Name: [Redacted]
Version: 2.0.0-beta.30
Author URL: [Redacted]
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.9.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL :[Redacted]
Subscription Statuses: wc-active: 1
wc-on-hold: 2

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Subscriptions by Payment Gateway ###

PayPal Standard: wc-active: 1
Stripe: wc-on-hold: 2

### Payment Gateway Support ###

PayPal Standard: subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_delayed_change
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ✔ Yes
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

### Product Bundles ###

Database Version: 6.5.1
Loopback Test: ✔
Template Overrides: –

### All Products for WooCommerce Subscriptions ###

Template Overrides: –
```

**Comment by rashmimalpande** [comment]
@apeksha10 Please test the holiday deletion part as well
