### ISSUE TITLE
Some notices appear on the checkout page when the current delivery date is set as a holiday.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#301]
**Describe the bug**
Some notices appear on the checkout page when the current delivery date is set as a holiday.

**To Reproduce**
1. Current delivery date set as a holiday
2. date and time slot set up
3. go to the checkout page, some notices are appears
see the screenshot: https://www.screencast.com/t/B5CJ5YKx2X

**Expected behavior**
No notice appears from our plugin 

Note: Doing basic testing with WP 5.6 beta copy.
I check the above issue with WP 5.5.3 but not able to replicate

**Comment by rashmimalpande** [comment]
This issue was fixed in v3.11.5 - https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/issues/309
