### ISSUE TITLE
Wrong Timeslot list has been displayed while hovering it on delivery date.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#306]
**Describe the bug**
Wrong Timeslot list has been displayed while hovering it on delivery date.

**To Reproduce**
Note: Minimum Delivery time (in hours): 4 
1- the problem appears on last 30 min of the day, before entering new date  (from 11:30 pm to 11:59 every day)
2- the current date will show booked for no reason
3- the next date show the wrong time slots
4- everything will be fixed after we enter new date (the plugin work perfect from 12:00AM to 11:29PM)
Attached one picture shows everything
![full problem](https://user-images.githubusercontent.com/15136179/103790040-b7795300-5066-11eb-8026-68c6457ad98d.png)

I could also replicate the issue where the wrong timeslots have been displayed but I am not able to replicate the issue of 'Booked' status.

**WordPress Environment**
Setting: 
[orddd-export-delivery-settings.zip](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/files/5776798/orddd-export-delivery-settings.zip)

```
**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/24278

**Comment by nitin-ts** [comment]
Hello,
this is working fine on my local setup so I am closing this issue.
