### ISSUE TITLE
Editing a page with Elementor the process gets stuck and throw some syntax error when our plugin is activated

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#330]
**Describe the bug**
Editing a page with Elementor the process gets stuck and throw some syntax error when our plugin is activated

**To Reproduce**
1. On staging I have only the Elementor lite and the WC plugin is activated.
2. The Cart page and checkout page. I could edit both pages with the Elementor plugin
3. Then I activated ORDD LITE and selected the delivery date on the checkout page.
4.  I can't edit the checkout page with the Elementor plugin

Note: I can check once by removing the delivery date from the session. https://www.screencast.com/t/cd75khZx0lm

See this video for better understanding: https://drive.google.com/file/d/1PZbXmphCjPxQxC94YLR2l-gyIQ_E2fV8/view

**Expected behavior**
The editing page should work fine with or without our plugin and no Syntax error should be received.

https://wordpress.org/support/topic/conflict-with-elementor-46/

**Comment by Chetna1510** [comment]
One more client has reported this: https://tychesoftwares.freshdesk.com/a/tickets/29636

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/38883
