### ISSUE TITLE
I am able to place an order on the site even though cut off time has been reached

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#331]
**Describe the bug**
I set the “Minimum delivery time” to 27 hours so that a user who orders cannot be delivered the next day if he orders after 9pm and it works,

but if the user arrives on the checkout page before 9pm and stays on this page, he can order after 9pm and choose the date of the next day (the order is made for example at 10:30pm for the next day while the minimum delivery time is 27 hours).

How to update the dates in the calendar at 9pm so that he can’t choose the next day’s date (according to the minimum delivery time) and prevent the order if the minimum delivery time is wrong ?

**To Reproduce**
I am also able to replicate it at our staging site.

**Additional context**
https://wordpress.org/support/topic/date-still-available-if-you-stay-on-the-checkout-page/

**Comment by apeksha10** [comment]
Re-opening this issue,

Now Plugin does not allow me to place an order but the wrong validation message appears 
See the screenshot: https://www.screencast.com/t/nOtLu2oHv3

Note : I didn't set any timeslot
