### ISSUE TITLE
Number of dates to choose do not include holiday days.

### ISSUE THREAD

**Issue by michaelbragg** [TycheSoftwares/order-delivery-date-for-woocommerce#337]
**Describe the bug**
When "Number of dates to choose" is set to 7 and 1 holiday date is within this date range the last date that can be choosen is 8 days.

**To Reproduce**
1. Order Delivery Date General Settings > Date Settings
2. Number of dates to choose: 7
3. Save settings
4. Order Delivery Date General Settings > Holidays
5. Add holiday date that is 3 days in the future. (30 May)
6. Save Settings
7. Visti checkout to select date

**Expected behavior**
I'd expect the date selector to show 6 avaiable dates with the holiday date showing as unavailable.
(29 May, 31, May, 1 June, 2 June, 3 June, 4 June)

Not 7 selectable dates (29 May, 31, May, 1 June, 2 June, 3 June, 4 June, 5 June)

**Screenshots or Video**

![Screenshot 2021-05-27 at 4 39 56 pm](https://user-images.githubusercontent.com/1015212/119856012-4d285880-bf0a-11eb-8f95-bdb19528ebf8.png)
![Screenshot 2021-05-27 at 4 40 00 pm](https://user-images.githubusercontent.com/1015212/119856022-4e598580-bf0a-11eb-9dbf-878478f309c9.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

**Comment by ashokrane** [comment]
@michaelbragg Thank you for reporting this. We are taking this up & will fix it by the next week.

**Comment by ashokrane** [comment]
@nitin-ts Please add this filter `orddd_is_holidays_excluded_from_dates_to_choose` on the plugin's Wiki page.

**Comment by nitin-ts** [comment]
I have added the filter on the wiki page.
