### ISSUE TITLE
The delivery date does not get block even if the time slot for that delivery date is reached the lockout value.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#341]
**Describe the bug**
The delivery date does not get block even if the time slot for that delivery date is reached the lockout value.

**To Reproduce**
1. Set time slot lockout value as 1 
2. Place an order for the date of 23rd June with a time slot 18:00-19:00
3. Again visit the same product checkout page, I noticed that the 23rd June delivery date is populating on the checkout page with a "No time slots re available" message.

https://www.screencast.com/t/I3VnCkiM
https://www.screencast.com/t/28bvJ2bL0s

Setting screenshot: https://www.screencast.com/t/fuIvZid9
https://www.screencast.com/t/d9OzBH8r1Tx

**Expected behavior**
The delivery date should be blocked if all time slots are blocked.

Note: I am doing testing PHP 8.0 with a live copy but I don't think that the above issue is related to PHP 8.0.

**Comment by nitin-ts** [comment]
hello,

I have checked this issue and it is behaving the same as in the pro version of the plugin. Below is the screenshot of the pro plugin.
https://i.imgur.com/51EAklB.png

So, I am moving this to a future milestone for now.

@rashmimalpande please let me know that if we should fix this issue in a future release or let the functionality as it is?

**Comment by PradeepTyche** [comment]
Works fine

2 timeslots each weekday
https://www.screencast.com/t/6kGkRMBJRlDf

1 order for each time slot on 23rd
https://www.screencast.com/t/uOzkJeyz

23rd is blocked in calendar
https://www.screencast.com/t/LfCxOXqKYlS

23rd is in blocked days
https://www.screencast.com/t/H87tNgfVRb

Worked with 1 slot for a day with 24 hour format too. Even default date selected si fine too.

https://www.screencast.com/t/8cs2WdeAx
https://www.screencast.com/t/kNF89GNO

https://www.screencast.com/t/jACiXVgX
https://www.screencast.com/t/sjG3clo3qu
