### ISSUE TITLE
Allow to translate below strings

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#357]
**Describe the bug**
I want to translate this text https://prnt.sc/1j7vf2j and also the text in the email that notifies the customer when the delivery date is updated.

**Additional context**
https://wordpress.org/support/topic/translate-391/

**Comment by apeksha10** [comment]
I have taken the latest git copy but still, some strings do not get translated.

see the screenshot: https://www.screencast.com/t/RCJwzBcr7fc

Hence I have re-open this issue.
