### ISSUE TITLE
Number of dates are blocked after updating the plugin.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#381]
**Describe the bug**
For the current month, number of dates are blocked - https://prnt.sc/1r3kbox
Also, I was unable to select any dates after October Month even though I set number of dates to choose 365: https://prnt.sc/1r3kbox

**To Reproduce**
I'm also able to replicate the issue just after updating the plugin version to 3.15.0
My setup: https://prnt.sc/1r3kg7i

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://wordpress.org/support/topic/dates-blocked-on-checkout-page/

**Comment by Chetna1510** [comment]
https://wordpress.org/support/topic/dates-are-blocked/

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/32501

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/32547

**Comment by oluisrael11** [comment]
Another client complained of this. [https://tychesoftwares.freshdesk.com/a/tickets/32519](https://tychesoftwares.freshdesk.com/a/tickets/32519)

**Comment by oluisrael11** [comment]
Another client complained of this. [https://tychesoftwares.freshdesk.com/a/tickets/32528](https://tychesoftwares.freshdesk.com/a/tickets/32528)

**Comment by oluisrael11** [comment]
Another client also complained about this. [https://tychesoftwares.freshdesk.com/a/tickets/32517](https://tychesoftwares.freshdesk.com/a/tickets/32517)
