### ISSUE TITLE
Shipping Days Settings redirect the wrong documentation link when I try to click on the arrow link.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#393]
**Describe the bug**
Shipping Days Settings redirect the wrong documentation link when I try to click on the arrow link.

**To Reproduce**
1. Upload the latest git copy
2. Go to the Shipping Days settings menu, when I try to click on the arrow link the plugin redirects me to the wrong page.

see the screenshot: https://www.screencast.com/t/FAtQQ2IixuTt
After clicking on this arrow the plugin redirects me to this page. https://www.screencast.com/t/jcCRCu06

**Expected behavior**
The plugin should redirect to  the correct page that is 'Setup Business days page' https://www.screencast.com/t/ArZ0rkFi7

**Comment by nitin-ts** [comment]
Hello,

this issue has been fixed in issue #394 so I am closing this issue.
