### ISSUE TITLE
More distance between the Specific Delivery Date Text and Specific delivery dates setup box.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#395]
**Describe the bug**
Distance should be less between the Specific Delivery Date Text and Specific delivery dates setup box.

see the screenshot: https://www.screencast.com/t/sn3Fn5hRnsP

**Expected behavior**
Distance should be less between the Specific Delivery Date Text and Specific delivery dates setup box.

**Comment by ashokrane** [comment]
@apeksha10 There is no need to add these UI issues as we are going to change the plugin UI for both Orddd Lite & Pro versions. We can avoid spending any time on such issues.
