### ISSUE TITLE
Wrong delivery date language appears on the order received page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#397]
**Describe the bug**
Wrong delivery date language appears on the order received page.

**To Reproduce**
1. I have set the delivery date language as the Portuguese language.
2. Go to checkout page, the delivery calendar shows the correct lanaguage.
3. Placed an order but the order received page shows the wrong delivery date language.

see the screenshot: https://www.screencast.com/t/Nc70WpJHW
https://www.screencast.com/t/pUpaU2M9xoq2

Email notification: https://www.screencast.com/t/ubW3DTsVR
https://www.screencast.com/t/zfhp9Xs55wv3

**Expected behavior**
Correct delivery date language should appear on the order received page.

**Comment by nitin-ts** [comment]
Hello,

I have checked this issue with the latest Git and it is working fine for me.

please see the below video:
https://www.screenpresso.com/=nFjSd

So, I am closing this issue.

**Comment by apeksha10** [comment]
I am able to replicate the above issue after taking the latest git copy

See the video: https://www.screencast.com/t/E9HdxCpsCnj

Note: I have checked your video too but I think the plugin works fine with the Hindi language. 

Hence I have re-open the issue.
