### ISSUE TITLE
The console shows some errors while the 'Additional Settings' page is load.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#405]
**Describe the bug**
The console shows some errors while the 'Additional Settings' page is load.

**To Reproduce**
1. Go to the Additional setting page
2. Console shows some errors. see the screenshot: https://www.screencast.com/t/8XGUcBN8

**Expected behavior**
No error must be thrown from our plugin.

**Comment by nitin-ts** [comment]
Hello,

with the latest Git copy, I can not replicate this issue. 

Please see the below video => https://www.screenpresso.com/=tVQI

so I am closing this issue.
