### ISSUE TITLE
Option “Disable for virtual products” is not working for simple products (also not for variations)

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#414]
**Describe the bug**
we are selling virtual products and also products with virtual variations.

In both cases the delivery date field is still displayed in checkout even though the option “Disable the Delivery Date and Time Slot Fields for: Virtual Products” is active.

You can reproduce this behavior in your demo, too. I just created a simple product and set it to virtual with the plugin option mentioned above enabled.

I had an older version installed and there I fixed it with a condition:

public static function orddd_lite_is_delivery_enabled() {
[...]
if ( 'on' === $fields_for_virtual_product && 'on' === $fields_for_featured_product ) {
				foreach ( $woocommerce->cart->get_cart() as $cart_item_key => $values ) {
                    $product_id = $values['variation_id'] > 0 ? $values['variation_id'] : $values['product_id'];
class-orddd-lite-common.php line 519.

But since the update to 3.16.0 it looks like the function orddd_lite_is_delivery_enabled() is completely ignored.

**To Reproduce**
I'm also able to replicate this issue on my staging site where the delivery date field appears on the checkout page for virtual products.

**Additional context**
https://wordpress.org/support/topic/option-disable-for-virtual-products-not-working-also-not-for-variations/

**Comment by Chetna1510** [comment]
One more client has reported this isuse: https://tychesoftwares.freshdesk.com/a/tickets/35038

**Comment by oluisrael11** [comment]
Another client reported this issue — [https://tychesoftwares.freshdesk.com/a/tickets/35266](https://tychesoftwares.freshdesk.com/a/tickets/35266)

**Comment by Chetna1510** [comment]
Another client has reported this - https://tychesoftwares.freshdesk.com/a/tickets/36263

**Comment by Chetna1510** [comment]
It's not working for feature products too - https://wordpress.org/support/topic/disable-the-delivery-date-for-featured-products-not-working/

**Comment by Chetna1510** [comment]
https://wordpress.org/support/topic/delivery-date-field-does-not-disappear-in-virtual-products/
