### ISSUE TITLE
Delivery Date Placeholder text is not appearing in the field on the checkout page. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#416]
**Describe the bug**
 I filled in at the backend of the website in the ‘placeholder text’ field is not shown at the frontend of the website. 

**To Reproduce**
I'm able to replicate the issue on my Local server.

1. Placeholder text is added : https://prnt.sc/20x6ll8
2. See on the checkout page as a guest user: https://prnt.sc/20x6lty

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/35662

**Comment by oluisrael11** [comment]
Another user has reported this issue. The placeholder text resets to the default text on the checkout page.

[https://tychesoftwares.freshdesk.com/a/tickets/39235](https://tychesoftwares.freshdesk.com/a/tickets/39235)

**Comment by oluisrael11** [comment]
Another user has reported this issue — [https://tychesoftwares.freshdesk.com/a/tickets/40087](https://tychesoftwares.freshdesk.com/a/tickets/40087)
