### ISSUE TITLE
Delivery date field can only be opened and closed once on checkout, after installing wordpress 5.9

### ISSUE THREAD

**Issue by lukas-blaue** [TycheSoftwares/order-delivery-date-for-woocommerce#419]
**Describe the bug**
Delivery date field can only be opened and closed once on checkout, after installing wordpress 5.9.
Closing the delivery date field causes "Uncaught TypeError: arguments.callee.caller is null"

**To Reproduce**
1. Have wordpress 5.9, latest version of woocommerce and order delivery date
2. Open the delivery date selector box by clicking on the field.
3. Close the box in any way (click outside the box, clear date or select a date)
4. "Uncaught TypeError: arguments.callee.caller is null" is triggered in the console

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/98881548/152137600-4b8052ff-c5d5-4159-843d-7d94166c4b5d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser: Chrome, Firefox
 - Version: latest

**Isolating the problem (mark completed items with an [x]):**
- [ X ] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [ X ] This bug happens with a default WordPress theme active, or [Storefront]
- [ X ] I can reproduce this bug consistently using the steps above

**Comment by PradeepTyche** [comment]
Not happening/ Can't replicate the issue locally.

https://www.screencast.com/t/XhazMHFm8z

**Comment by ashokrane** [comment]
Hi @lukas-blaue, Thank you for reporting this issue. We have fixed it in our latest plugin update v3.16.1. Please update the Order Delivery Date plugin to the latest version.

**Comment by lukas-blaue** [comment]
Thanks for the fast response and fix
