### ISSUE TITLE
The delivery date is different on WooCommerce Order page than the WooCommerce Edit Order page.

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/order-delivery-date-for-woocommerce#424]
**Describe the bug**
The selected delivery date shows one day early on the order confirmation screen on the website, the order page and the customer invoice. The chosen delivery date shows correctly in the pick-up date field.

![image](https://user-images.githubusercontent.com/12012702/154044468-9f50e705-4bf0-44f2-9d8c-4934951e1eb4.png)
![image](https://user-images.githubusercontent.com/12012702/154044499-324b36b4-0426-40ff-ae4d-70672571613f.png)

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/38129](https://tychesoftwares.freshdesk.com/a/tickets/38129)

**Comment by PradeepTyche** [comment]
Could not replicate.  Could not replicate.
