### ISSUE TITLE
Time slots not coming up for the first available delivery date on the delivery calendar

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/order-delivery-date-for-woocommerce#438]
**Describe the bug**
Time slots do not come up for the first available delivery date on the delivery calendar when the minimum delivery time feature is active.

**To Reproduce**
1. Enable two (2) days, Thursday and Friday, as delivery days.
2. Add a minimum delivery time of 144 hours. 
3. Go to the time slots section _(General Settings >> Time slot)_ and set time slots as preferred.
4. Add a product to the cart, navigate to the checkout page and see the error on the first available delivery day (Thursday). The time slots won't show up.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/40027](https://tychesoftwares.freshdesk.com/a/tickets/40027)

**Comment by PratapDungrani** [comment]
@oluisrael11  I am not able to replicate the issue. Here are the screenshots
https://www.screenpresso.com/=hxJId
https://www.screenpresso.com/=r3mef
https://www.screenpresso.com/=R4aWf
https://www.screenpresso.com/=9Rpde

**Comment by nitin-ts** [comment]
I can replicate this issue.

I have Saturdays and Sundays enabled with 148 MDT and a time slot from 9 am to 8 pm 

https://i.imgur.com/KrALil9.png
https://i.imgur.com/U1rhs9J.png

When I open a checkout page then I can select 25th Sept but it is not showing any time slot 
https://i.imgur.com/BglBOqM.png

It must disable the day if all time slots for the day are passed.

I am re-opening this issue.
