### ISSUE TITLE
Getting error on checkout page - The cut-off time for the selected date has expired. Please select another delivery date.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#446]
**Describe the bug**
Unable to place an order and getting error - The cut-off time for the selected date has expired. Please select another delivery date.

**To Reproduce**
Do the setup like this: https://bit.ly/3Myf8Af

Today is 28th April, the first available date is 29th April. 

After selecting the date and after trying to place an order, an error message has appeared - https://prnt.sc/_zCosF3d7Ot5

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/40621

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/40616

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/40633

**Comment by Chetna1510** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/40787

**Comment by PradeepTyche** [comment]
Hi @Chetna1510 the client in above issue, 40787,  is using Pro version. You need to create a different ticket for this.
