### ISSUE TITLE
Getting error - The cut-off time for the selected date has expired. Please select another delivery date.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#455]
**Describe the bug**
Getting error - The cut-off time for the selected date has expired. Please select another delivery date.

**To Reproduce**
1. Auto-populate first available Delivery date is disabled
2. Don't Select any date
3. you'll see this error - https://prnt.sc/DMBBP4gUOZL7

**Expected behavior**
It should show "Delivery Date Field is expired" message only.

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/40672

**Comment by PradeepTyche** [comment]
closed as it is same as 446, 450
