### ISSUE TITLE
Plugin throw "The selected time slot has expired. Please select another time slot for delivery." error. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#463]
**Describe the bug**
Plugin throw "The selected time slot has expired. Please select another time slot for delivery." error. 

**To Reproduce**
1. Date and time slot setup
2. ASAP option enabled 
3. Auto-populate delivery date is disabled 
4. MDT set as 24 hours 
5. Add the product 
6. Check out the page, throw me this error. "The selected time slot has expired. Please select another time slot for delivery." even though I have selected the ASAP option. 
see the screenshot : https://www.screencast.com/t/eTDPCL5hwb

**Expected behavior**
The plugin should allow the users to place an order without any error.

Plugin Setting video : https://www.screencast.com/t/ReeIeXovt5d

**Comment by PradeepTyche** [comment]
Not replicated.
