### ISSUE TITLE
Delivery field skipped even though made mandatory

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/order-delivery-date-for-woocommerce#475]
**Describe the bug**
The delivery date mandatory validation feature no longer works on the checkout page when activated. This means that customers can successfully checkout without having to select a delivery date even though it is mandatory.

— To replicate this issue, just install and activate the Order Delivery Date for WooCommerce. Thereafter, ensure that the 'Mandatory field' under General Settings >> Date Settings is checked.

— Navigate to the frontend, select any product, add to the cart and proceed to the checkout page. Fill in the necessary details on the checkout page but do not select any delivery date. In other words, skip the option to select a delivery date and confirm order. The checkout process will be completed.

**Expected behavior**
The validation check should work and not allow the checkout process to be completed except the delivery date is selected.

**Additional context**
[https://wordpress.org/support/topic/delivery-field-skipped-even-though-made-mandatory/#post-16213556](https://wordpress.org/support/topic/delivery-field-skipped-even-though-made-mandatory/#post-16213556)

**Comment by ashokrane** [comment]
@oluisrael11 Since you have been able to replicate this, It's important to mention the same in the issue itself.

**Comment by oluisrael11** [comment]
@ashokrane The issue has been updated.
