### ISSUE TITLE
Not able to create bulk time slots. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#479]
**Describe the bug**
Not able to create bulk time slots. 

**To Reproduce**
1. HPOS setup 
2. Go to the time slots page and try to add a Bulk time slot using the "Add time slot in bulk" button 
3. Put all information 
4. I clicked on the 'Save setting' button but the bulk time slot does not create.

No console error was found 
Debug log errors : [28-Nov-2022 09:23:23 UTC] Cron reschedule event error for hook: orddd_lite_ts_tracker_send_event, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"once_in_week","args":[],"interval":604800} 

**Expected behavior**
The bulk time slots feature should work fine.

**Comment by nitin-ts** [comment]
Hello,

I have checked this issue with the latest Git copy in the HPOS setup and I am not able to replicate it hence closing it.

Here is the video => https://www.screenpresso.com/=6Dx0f
