### ISSUE TITLE
Search Order filter does not work correctly. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#496]
**Describe the bug**
The search Order filter does not work correctly. 

**To Reproduce**
1. Go to the Woo_order page
2. I try to search today/tomorrow dates for example. 7th July. search box order shows 7th July orders + 27th July orders. 
https://app.screencast.com/LYYIiQfNi7XGU

For 8th July, the search order shows like this. https://app.screencast.com/OVQQt8JbofQq3

**Expected behavior**
The search Order filter should work properly.

**Comment by rashmimalpande** [comment]
The search box does not search for the exact string. It will display the results which has date similar to the searched one. We can use the custom filter for the exact date search.
