### ISSUE TITLE
The number of dates to choose feature is not working. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#497]
**Describe the bug**
The number of dates to choose feature is not working. 

**To Reproduce**
1. Select 'Number of dates to choose -10
2. Add the product 
3. Go to the checkout page the delivery calendar shows only 8 delivery dates to choose.  https://app.screencast.com/I2vaSq3wygcBC

Settings : https://app.screencast.com/1FYpgze87C15G, https://app.screencast.com/JuavmDzLVaOAk
https://app.screencast.com/kKvH7ZP58hvb7, https://app.screencast.com/ynCRZf1xHoHB8
https://app.screencast.com/MZi2DtqxxHMLh

**Expected behavior**
The number of dates to choose feature should work fine.

**Comment by nidhitatosaniya** [comment]
This issue is not replicate at my end with all same setup.
