### ISSUE TITLE
Unable to sort the delivery dates on WooCommerce Order page

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#503]
**Describe the bug**
The Delivery date plug in when you filter the right hand side it doesn't change the dates in order.

![image](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/36bc840b-2851-4607-90b0-53c144ced935)

**To Reproduce**
I'm able to replicate the issue on the staging site where I'm unable to sort the orders by delivery date.

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**WordPress Environment**
<details>
```
**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/56804

**Comment by rashmimalpande** [comment]
The sorting won’t work when ‘Enable default sorting of orders (in descending order) by Delivery Date on WooCommerce -> Orders page’ setting is disabled. Please check it by enabling this setting. It works fine when enabled.

**Comment by ashokrane** [comment]
@rashmimalpande @upenkapse @Chetna1510 Should we get rid of this setting & have it always enabled? Whether to sort it or not is upto the store admin. But by default, we can remove this setting & keep it enabled? The idea is to get rid of something obvious & not need to have a setting.

**Comment by rashmimalpande** [comment]
@ashokrane I agree. We can remove this setting from both lite & pro version.

**Comment by Chetna1510** [comment]
@ashokrane Yes, definitely we can remove that setting.  

@rashmimalpande Even with "Enable default sorting of orders (in descending order) by Delivery Date on WooCommerce -> Orders page’ setting" setting enabled, sorting was not working. It seems the issue is with HPOS. If you will enable HPOS, it creates an issue.

**Comment by oluisrael11** [comment]
@ashokrane @rashmimalpande I'm also in support of removing the setting and enabling the order sorting enabled by default. It doesn't seem like it will affect anything, nor will users have an issue with the sorting if the setting is removed.

**Comment by upenkapse** [comment]
> @rashmimalpande @upenkapse @Chetna1510 Should we get rid of this setting & have it always enabled? Whether to sort it or not is upto the store admin. But by default, we can remove this setting & keep it enabled? The idea is to get rid of something obvious & not need to have a setting.

This setting is needed because it not only sorts the orders when the Delivery Date sorting is used manually but as the name of the setting suggests it sorts the orders in descending order based on the delivery date selected in the orders. 

It changes the default WooCommerce order sorting of recent orders first so we should not overwrite this default WooCommerce sorting without giving them an option.

**Comment by ashokrane** [comment]
Sorry guys. I misunderstood the setting that it is just used to make the delivery date field as sortable. I now have checked it's label (as @upenkapse said): "Enable default sorting of orders (in descending order) by Delivery Date on WooCommerce -> Orders page" . So removing it & enabling by default may not be a right decision.

https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/issues/503#issuecomment-1704647043 - @rashmimalpande Even if this setting is disabled, the sorting on the delivery date field should still work. The only thing this setting is supposed to do is show the order sorted by delivery date by default i.e when the Orders page loads. This setting shouldn't affect the behaviour when someone clicks on the Delivery Date column heading (to sort the orders) on the Orders page. 

@upenkapse 

> This setting is needed because it not only sorts the orders when the Delivery Date sorting is used manually
On the same lines as I mentioned to Rashmi above, I don't think this setting should be needed to sort the orders by delivery date manually.

**Comment by Chetna1510** [comment]
The issue is still there when HPOS is enabled. 

When HPOS is disabled:
![image](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/1e22ed74-b49d-4f35-a0f0-198b821f43af)

When HPOS enabled:

![image](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/a5ade14e-3a79-4871-b556-d1b1819878e5)

So, I'm going to reopen this.
