### ISSUE TITLE
The delivery date field is not visible on the checkout block page. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#510]
**Describe the bug**
The delivery date field is not visible on the checkout block page. 

**To Reproduce**
1. Create a cart and checkout block page 
2. Add the product 
3. Go to the checkout block page, the delivery date is not visible. https://app.screencast.com/M4mnq2er7Fluv

**Expected behavior**
The delivery date field should be visible on the checkout page.

**Comment by oluisrael11** [comment]
Another user reported this issue - [https://wordpress.org/support/topic/not-appearing-when-checkout-blocks-activated/](https://wordpress.org/support/topic/not-appearing-when-checkout-blocks-activated/)

**Comment by oluisrael11** [comment]
Another user reported this issue - [https://tychesoftwares.freshdesk.com/a/tickets/60622](https://tychesoftwares.freshdesk.com/a/tickets/60622)
