### ISSUE TITLE
Feedback for the Deactivation survey - add a Skip & Deactivate button.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#511]
Please add a "Skip & Deactivate" button to your Freemius (or similar) instance. I truly hate being forced to provide feedback ("Why are you disabling this plugin?") when disabling plugins, especially during troubleshooting.

I'm filing this ticket under "Bug", because requesting for invasive telemetry to be skippable, should not be a feature request. It should already be there.

https://tychesoftwares.freshdesk.com/a/tickets/59919

**Comment by nidhitatosaniya** [comment]
Attached PR : https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/pull/514
