### ISSUE TITLE
The Calendar not displaying for Delivery Date Selection.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#512]
**Describe the bug**
I've been a long-time user of your plugin, and it has been functioning flawlessly until recently. Since last Friday, I've encountered an issue where the calendar for selecting the shipment date is not being displayed. Consequently, this prevents the selection of the collection time as well.

**To Reproduce**
I can replicate this issue on client's site only.

1. Nevigate to Checkout page
2. Try to select Delivery Date:
![image (4)](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/09281845-98d3-40a1-94cf-fe5135fb3345)

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/59998

**Comment by nidhitatosaniya** [comment]
An error comes in console when the holiday name contains double quotes in it.
