### ISSUE TITLE
Delivery calendar not showing up on the checkout page

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/order-delivery-date-for-woocommerce#518]
**Describe the bug**
There is an issue on one of our user's sites where the delivery calendar does not appear on the checkout page.

So far, this can only be recreated on the client's site.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/61024](https://tychesoftwares.freshdesk.com/a/tickets/61024)
[https://tychesoftwares.freshdesk.com/a/tickets/62225](https://tychesoftwares.freshdesk.com/a/tickets/62225)

**Comment by oluisrael11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub issue - 518](https://trello.com/c/b2pOIBSc/142-github-issue-518)

**Comment by nidhi-tatosaniya** [comment]
The Delivery Date field displaying correctly on checkout page. it's a cache issue on client site. see here 
![image](https://github.com/user-attachments/assets/3309e92d-c7d4-421c-9276-fc221abff572)
