### ISSUE TITLE
Deactivation Reasons are not correct in the plugin

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#521]
**Describe the bug**
Deactivation Reasons are not correct in the plugin
1.  Custom Delivery Settings are not working.
2. The Shipping Day feature is not working.

These features are not available in the LITE version.

![image](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/assets/15136179/a3545041-cdd0-45be-90a5-8ebc692a218f)

**Comment by nidhitatosaniya** [comment]
The reasons are appearing correctly See here : https://prnt.sc/M2VpvF8gMUvt Hence I closing this.
