### ISSUE TITLE
Conflict issues with Gravity Form fields

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/order-delivery-date-for-woocommerce#531]
**Describe the bug**
There is an issue in which there is a conflict with the [Gravity Forms product form](https://woo.com/products/gravity-forms-add-ons/) and the Order Delivery Date for WooCommerce version 3.21.0. This also forces single product pages to stop working due to the following Javascript error:

> datepicker.min.js?ver=1.13.2:9 Uncaught Missing instance data for this datepicker
> _getInst	@	datepicker.min.js?ver=1.13.2:9
> orddd_lite_autofil_date_time	@	orddd-lite-initializ…r.js?ver=3.21.0:446
> load_lite_functions	@	orddd-lite-initializ…r.js?ver=3.21.0:394
> (anonymous)	@	orddd-lite-initializ…r.js?ver=3.21.0:131
> c	@	jquery.min.js:4
> fireWith	@	jquery.min.js:4
> ready	@	jquery.min.js:4
> q	@	jquery.min.js:4

**Additional context**
[https://wordpress.org/support/topic/frontend-javascript-error-conflicting-with-gravity-form-fields/#post-17473711](https://wordpress.org/support/topic/frontend-javascript-error-conflicting-with-gravity-form-fields/#post-17473711)

**Comment by nidhi-tatosaniya** [comment]
The fix included in [This PR](https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/pull/548)
