### ISSUE TITLE
Delivery date is reverting to previously selected Date on Cart block page.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/order-delivery-date-for-woocommerce#532]
**Describe the bug**
After selecting a new date for the order delivery, the chosen date changes back to a previously picked date once a time slot is selected for the newly chosen date.

**To Reproduce**
1. Create Cart Block page.
2. Setup timeslot and enable the option "Delivery Date field on Cart page:" to show delivery date field on cart page. 
3. Go to Cart Block page. 
4. You might have previously selected delivery date or first available delivery date. Please select another delivery date:
https://prnt.sc/4NBSqBulKM8w
4. After that, select timeslot and notice the behavior of delivery date. The selected delivery date reverts to a previously picked date.

I'm also able to replicate on my staging site.

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://support.tychesoftwares.com/conversation/952?folder_id=9

**Comment by Chetna1510** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github issue - 532](https://trello.com/c/c58OY2iU/153-github-issue-532)

**Comment by nidhitatosaniya** [comment]
The issue is replicated only when 'Auto-populate first available Delivery time slot when the date is selected on the checkout page.' setting is  enabled. https://prnt.sc/_3gHy-IoXKM_
