### ISSUE TITLE
Encountering a "500 Internal Server Error" after uploading the latest live copy (3.21.0)

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/order-delivery-date-for-woocommerce#540]
**Describe the bug**
Encountering a "500 Internal Server Error" after uploading the latest live copy (3.21.0)

**To Reproduce**
1. Installed 3.21.0 live copy
2. WP 6.5 RC 3 copy installed and WC 8.7.0
3. I noticed 500 Internal Server Error. https://prnt.sc/X7EYngAt3cnc 

**Expected behavior**
No error must be thrown from our plugin. 

Note: This issue is replicated with WP 6.4.3.

**Comment by nidhi-tatosaniya** [comment]
The above issue is not replicated with WP 6.6, WC 9.1.2 & latest master copy & live. Hence I closing it.
