### ISSUE TITLE
Language change on plugin activation forces some order statuses forcefully translated

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/order-delivery-date-for-woocommerce#545]
**Describe the bug**
There is an issue that forces the language on some of the order statuses to be translated whenever translation plugins (such as WPML, Loco Translate) and Order Delivery Date Lite are present and active. 

On one of the affected users' sites, the dates and the order statuses on the WooCommerce order list change from the default language (Spanish) to English. This is also considering the fact that the affected user uses the Loco Translate plugin but doesn't use it to translate the WooCommerce plugin strings.

This issue is similar to the one fixed in the PRO version here in [#6623](https://github.com/TycheSoftwares/order-delivery-date-pro/issues/6623) that also had to do with the order status translation when translation plugins are active.

**To Reproduce**
Activate any translation plugins and the Order Delivery Date Lite plugin.

**Additional context**
[https://wordpress.org/support/topic/language-change-on-activation/#post-17787882](https://wordpress.org/support/topic/language-change-on-activation/#post-17787882)

**Comment by oluisrael11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub issue - 545](https://trello.com/c/8RGSGweE/168-github-issue-545)

**Comment by oluisrael11** [comment]
Another client reported this issue — [https://support.tychesoftwares.com/conversation/2841](https://support.tychesoftwares.com/conversation/2841)

**Comment by Chetna1510** [comment]
https://wordpress.org/support/topic/admin-order-list-view-status-button-translation-messed-up/
