### ISSUE TITLE
Update documentation for UI change 

### ISSUE THREAD

**Issue by mokshasharmila13** [TycheSoftwares/order-delivery-date-for-woocommerce#564]
## Link to the Page/Section

This is the link for the Ordd Lite docs: [ https://www.tychesoftwares.com/docs/woocommerce-order-delivery-date-lite/]

![image](https://github.com/user-attachments/assets/cdda3ef9-7fe5-43e9-ab58-b94a0ddb09c2)

New UI look 

![image](https://github.com/user-attachments/assets/d6d058c0-eebe-402a-a576-33878e62b06f)

## Description of the Suggestion

Please update the documents with the new images and update the tab names. Also, the file path needs to be corrected in the documents.

## Reason for the Suggestion

The UI for the ordd lite plugin has been updated, and the tabs' labels have also been changed. Therefore, the images should be updated to reflect these new UI changes.

**Comment by Chetna1510** [comment]
1. I updated **all** the documentation with new Images
2. Arranged documentation in a better manner
3. Added some missed feature descriptions in the respective documentation
4. Published Timeslot Feature - https://www.tychesoftwares.com/docs/docs/order-delivery-date-for-woocommerce-lite/timeslot-feature/

So, closing this one.
